[versions]
detekt = "1.23.8"
jdk-target = "17"
#kotest = "6.0.7"
kotlin = "2.2.21"
kotlinPoet = "2.2.0"
kotlinxCoroutinesCore = "1.10.2"
kotlinxKnit = "0.5.1"
kotlinxSerializationJson = "1.6.3"
ksp = "2.2.21-2.0.5"
ktfmt = "0.25.0"
maven-publish = "0.30.0"

[libraries]
#kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
#kotest-framework = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-poet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoet" }
kotlin-poet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinPoet" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesCore" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
maven-publish-plugin = { module = "com.vanniktech.maven.publish:com.vanniktech.maven.publish.gradle.plugin", version.ref = "maven-publish" }
symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

[plugins]
arturbosch-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ncorti-ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
#kotest = { id = "io.kotest", version.ref = "kotest" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinx-knit = { id = "org.jetbrains.kotlinx.knit", version.ref = "kotlinxKnit" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
