name: Push to all

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'corretto'
  XCODE_VERSION: '15.3'

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: ${{env.JAVA_DISTRIBUTION}}
          cache: gradle

      - name: Set up XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run ktfmt Checker
        run: ./gradlew ktfmtCheck

      - name: Run detekt
        run: ./gradlew detekt

      - name: Build and test
        run: ./gradlew build

      - name: Upload build reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: '**/build/reports'
