name: Publish Artifacts
on:
  release:
    types: [ published ]

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'corretto'
  XCODE_VERSION: '15.3'

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: ${{env.JAVA_DISTRIBUTION}}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Add Gradle Properties
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: |
          echo "mavenCentralUsername=${MAVEN_CENTRAL_USERNAME}" >> gradle.properties
          echo "mavenCentralPassword=${MAVEN_CENTRAL_PASSWORD}" >> gradle.properties
          echo "signing.keyId=${SIGNING_KEY_ID}" >> gradle.properties
          echo "signing.password=${SIGNING_KEY_PASSWORD}" >> gradle.properties
          echo "signing.secretKeyRingFile=${HOME}/secret_key.gpg" >> gradle.properties

      - name: Set up XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Setup GPG Key
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          brew install gpg
          echo "$SIGNING_KEY" | gpg --dearmor > ${HOME}/secret_key.gpg

      - name: Extract Release Version
        id: version
        run: echo "VERSION=${{ github.event.release.tag_name#v }}" >> $GITHUB_ENV

      - name: Publish To Maven Central
        env:
          VERSION_OVERRIDE: ${{ env.VERSION }}
        run: |
          ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
